services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    env_file:
      - .env
    volumes:
      - ./addons:/mnt/extra-addons
      - odoo-web-data:/var/lib/odoo

  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-web-data:
  odoo-db-data:
