services:
  web:
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./addons:/mnt/extra-addons
      - ./filestore:/var/lib/odoo/filestore

  db:
    image: postgres:13
    env_file:
      - .env
